class ItemsInfo{
    constructor()
    {
        this.iteminfo = {};
    }

    addItem(id, name , isBelowTierFour)
    {
        if(isBelowTierFour)
        {
            this.iteminfo[id] = name;
        } else {
            let code = id - 1;
            let itemNameBuilder = name.split('');
            let counter = 0;
     
            for (let i = 4; i <= 8; i++) {
                counter++;
                itemNameBuilder[1] = i.toString();
                this.iteminfo[code + counter] = itemNameBuilder.join('');

                for (let j = 1; j <= 4; j++) {
                    counter++;
                    name = itemNameBuilder.join('') + "@" + j;
                    this.iteminfo[code + counter] = name;
                }
            }
        }   
    }

    initItems()
    {
        this.addItem(1850, 'T4_OFF_SHIELD', false);
        this.addItem(1875, 'T4_OFF_TOWERSHIELD_UNDEAD', false);
        this.addItem(1900, 'T4_OFF_SHIELD_HELL', false);
        this.addItem(1925, 'T4_OFF_SPIKEDSHIELD_MORGANA', false);
        this.addItem(1950, 'T4_OFF_SHIELD_AVALON', false);
        this.addItem(1977, 'T4_OFF_BOOK', false);
        this.addItem(2002, 'T4_OFF_ORB_MORGANA', false);
        this.addItem(2027, 'T4_OFF_DEMONSKULL_HELL', false);
        this.addItem(2052, 'T4_OFF_TOTEM_KEEPER', false);
        this.addItem(2077, 'T4_OFF_CENSER_AVALON', false);
        this.addItem(2103, 'T4_OFF_TORCH', false);
        this.addItem(2128, 'T4_OFF_HORN_KEEPER', false);
        this.addItem(2153, 'T4_OFF_TALISMAN_AVALON', false);
        this.addItem(2178, 'T4_OFF_LAMP_UNDEAD', false);
        this.addItem(2203, 'T4_OFF_JESTERCANE_HELL', false);
        this.addItem(2228, 'T2_CAPE', true);
        this.addItem(2229, 'T3_CAPE', true);
        this.addItem(2230, 'T4_CAPE', false);
        this.addItem(2255, 'T4_CAPEITEM_FW_BRIDGEWATCH', false);
        this.addItem(2280, 'T4_CAPEITEM_FW_FORTSTERLING', false);
        this.addItem(2305, 'T4_CAPEITEM_FW_LYMHURST', false);
        this.addItem(2330, 'T4_CAPEITEM_FW_MARTLOCK', false);
        this.addItem(2355, 'T4_CAPEITEM_FW_THETFORD', false);
        this.addItem(2380, 'T4_CAPEITEM_FW_CAERLEON', false);
        this.addItem(2405, 'T4_CAPEITEM_FW_BRECILIEN', false);
        this.addItem(2430, 'T4_CAPEITEM_AVALON', false);
        this.addItem(2455, 'T4_CAPEITEM_HERETIC', false);
        this.addItem(2505, 'T4_CAPEITEM_KEEPER', false);
        this.addItem(2530, 'T4_CAPEITEM_MORGANA', false);
        this.addItem(2555, 'T4_CAPEITEM_DEMON', false);
        this.addItem(2582, 'T2_BAG', true);
        this.addItem(2583, 'T3_BAG', true);
        this.addItem(2584, 'T4_BAG', false);
        this.addItem(2609, 'T4_BAG_INSIGHT', false);
        this.addItem(3125, 'T2_HEAD_PLATE_SET1', true);
        this.addItem(3127, 'T4_HEAD_PLATE_SET1', false);
        this.addItem(3152, 'T2_ARMOR_PLATE_SET1', true);
        this.addItem(3154, 'T4_ARMOR_PLATE_SET1', false);
        this.addItem(3179, 'T2_SHOES_PLATE_SET1', true);
        this.addItem(3181, 'T4_SHOES_PLATE_SET1', false);
        this.addItem(3206, 'T4_HEAD_PLATE_SET2', false);
        this.addItem(3231, 'T4_ARMOR_PLATE_SET2', false);
        this.addItem(3256, 'T4_SHOES_PLATE_SET2', false);
        this.addItem(3281, 'T4_HEAD_PLATE_SET3', false);
        this.addItem(3306, 'T4_ARMOR_PLATE_SET3', false);
        this.addItem(3331, 'T4_SHOES_PLATE_SET3', false);
        this.addItem(3356, 'T4_HEAD_PLATE_UNDEAD', false);
        this.addItem(3381, 'T4_ARMOR_PLATE_UNDEAD', false);
        this.addItem(3406, 'T4_SHOES_PLATE_UNDEAD', false);
        this.addItem(3431, 'T4_HEAD_PLATE_HELL', false);
        this.addItem(3456, 'T4_ARMOR_PLATE_HELL', false);
        this.addItem(3481, 'T4_SHOES_PLATE_HELL', false);
        this.addItem(3506, 'T4_HEAD_PLATE_KEEPER', false);
        this.addItem(3531, 'T4_ARMOR_PLATE_KEEPER', false);
        this.addItem(3556, 'T4_SHOES_PLATE_KEEPER', false);
        this.addItem(3581, 'T4_HEAD_PLATE_FEY', false);
        this.addItem(3606, 'T4_ARMOR_PLATE_FEY', false);
        this.addItem(3631, 'T4_SHOES_PLATE_FEY', false);
        this.addItem(3656, 'T4_HEAD_PLATE_AVALON', false);
        this.addItem(3681, 'T4_ARMOR_PLATE_AVALON', false);
        this.addItem(3706, 'T4_SHOES_PLATE_AVALON', false);
        this.addItem(3734, 'T4_HEAD_LEATHER_SET1', false);
        this.addItem(3762, 'T4_ARMOR_LEATHER_SET1', false);
        this.addItem(3790, 'T4_SHOES_LEATHER_SET1', false);
        this.addItem(3815, 'T4_HEAD_LEATHER_SET2', false);
        this.addItem(3840, 'T4_ARMOR_LEATHER_SET2', false);
        this.addItem(3865, 'T4_SHOES_LEATHER_SET2', false);
        this.addItem(3890, 'T4_HEAD_LEATHER_SET3', false);
        this.addItem(3915, 'T4_ARMOR_LEATHER_SET3', false);
        this.addItem(3940, 'T4_SHOES_LEATHER_SET3', false);
        this.addItem(3965, 'T4_HEAD_LEATHER_MORGANA', false);
        this.addItem(3990, 'T4_ARMOR_LEATHER_MORGANA', false);
        this.addItem(4015, 'T4_SHOES_LEATHER_MORGANA', false);
        this.addItem(4040, 'T4_HEAD_LEATHER_HELL', false);
        this.addItem(4065, 'T4_ARMOR_LEATHER_HELL', false);
        this.addItem(4090, 'T4_SHOES_LEATHER_HELL', false);
        this.addItem(4115, 'T4_HEAD_LEATHER_UNDEAD', false);
        this.addItem(4165, 'T4_SHOES_LEATHER_UNDEAD', false);
        this.addItem(4190, 'T4_HEAD_LEATHER_FEY', false);
        this.addItem(4215, 'T4_ARMOR_LEATHER_FEY', false);
        this.addItem(4265, 'T4_HEAD_LEATHER_AVALON', false);
        this.addItem(4290, 'T4_ARMOR_LEATHER_AVALON', false);
        this.addItem(4315, 'T4_SHOES_LEATHER_AVALON', false);
        this.addItem(4342, 'T4_HEAD_CLOTH_SET1', false);
        this.addItem(4369, 'T4_ARMOR_CLOTH_SET1', false);
        this.addItem(4396, 'T4_SHOES_CLOTH_SET1', false);
        this.addItem(4421, 'T4_HEAD_CLOTH_SET2', false);
        this.addItem(4446, 'T4_ARMOR_CLOTH_SET2', false);
        this.addItem(4471, 'T4_SHOES_CLOTH_SET2', false);
        this.addItem(4496, 'T4_HEAD_CLOTH_SET3', false);
        this.addItem(4521, 'T4_ARMOR_CLOTH_SET3', false);
        this.addItem(4546, 'T4_SHOES_CLOTH_SET3', false);
        this.addItem(4571, 'T4_HEAD_CLOTH_KEEPER', false);
        this.addItem(4596, 'T4_ARMOR_CLOTH_KEEPER', false);
        this.addItem(4621, 'T4_SHOES_CLOTH_KEEPER', false);
        this.addItem(4646, 'T4_HEAD_CLOTH_HELL', false);
        this.addItem(4671, 'T4_ARMOR_CLOTH_HELL', false);
        this.addItem(4696, 'T4_SHOES_CLOTH_HELL', false);
        this.addItem(4721, 'T4_HEAD_CLOTH_MORGANA', false);
        this.addItem(4746, 'T4_ARMOR_CLOTH_MORGANA', false);
        this.addItem(4771, 'T4_SHOES_CLOTH_MORGANA', false);
        this.addItem(4821, 'T4_ARMOR_CLOTH_FEY', false);
        this.addItem(4846, 'T4_SHOES_CLOTH_FEY', false);
        this.addItem(4871, 'T4_HEAD_CLOTH_AVALON', false);
        this.addItem(4896, 'T4_ARMOR_CLOTH_AVALON', false);
        this.addItem(4921, 'T4_SHOES_CLOTH_AVALON', false);
        this.addItem(4946, 'T4_HEAD_CLOTH_ROYAL', false);
        this.addItem(4971, 'T4_ARMOR_CLOTH_ROYAL', false);
        this.addItem(4996, 'T4_SHOES_CLOTH_ROYAL', false);
        this.addItem(5021, 'T4_HEAD_LEATHER_ROYAL', false);
        this.addItem(5046, 'T4_ARMOR_LEATHER_ROYAL', false);
        this.addItem(5071, 'T4_SHOES_LEATHER_ROYAL', false);
        this.addItem(5096, 'T4_HEAD_PLATE_ROYAL', false);
        this.addItem(5121, 'T4_ARMOR_PLATE_ROYAL', false);
        this.addItem(5146, 'T4_SHOES_PLATE_ROYAL', false);
        this.addItem(5171, 'T4_HEAD_GATHERER_FIBER', false);
        this.addItem(5196, 'T4_ARMOR_GATHERER_FIBER', false);
        this.addItem(5221, 'T4_SHOES_GATHERER_FIBER', false);
        this.addItem(5246, 'T4_BACKPACK_GATHERER_FIBER', false);
        this.addItem(5271, 'T4_HEAD_GATHERER_HIDE', false);
        this.addItem(5296, 'T4_ARMOR_GATHERER_HIDE', false);
        this.addItem(5321, 'T4_SHOES_GATHERER_HIDE', false);
        this.addItem(5346, 'T4_BACKPACK_GATHERER_HIDE', false);
        this.addItem(5371, 'T4_HEAD_GATHERER_ORE', false);
        this.addItem(5396, 'T4_ARMOR_GATHERER_ORE', false);
        this.addItem(5421, 'T4_SHOES_GATHERER_ORE', false);
        this.addItem(5446, 'T4_BACKPACK_GATHERER_ORE', false);
        this.addItem(5471, 'T4_HEAD_GATHERER_ROCK', false);
        this.addItem(5496, 'T4_ARMOR_GATHERER_ROCK', false);
        this.addItem(5521, 'T4_SHOES_GATHERER_ROCK', false);
        this.addItem(5546, 'T4_BACKPACK_GATHERER_ROCK', false);
        this.addItem(5571, 'T4_HEAD_GATHERER_WOOD', false);
        this.addItem(5596, 'T4_ARMOR_GATHERER_WOOD', false);
        this.addItem(5621, 'T4_SHOES_GATHERER_WOOD', false);
        this.addItem(5646, 'T4_BACKPACK_GATHERER_WOOD', false);
        this.addItem(5671, 'T4_HEAD_GATHERER_FISH', false);
        this.addItem(5696, 'T4_ARMOR_GATHERER_FISH', false);
        this.addItem(5721, 'T4_SHOES_GATHERER_FISH', false);
        this.addItem(5746, 'T4_BACKPACK_GATHERER_FISH', false);
        this.addItem(5983, 'T4_2H_BOW', false);
        this.addItem(6008, 'T4_2H_WARBOW', false);
        this.addItem(6033, 'T4_2H_LONGBOW', false);
        this.addItem(6058, 'T4_2H_LONGBOW_UNDEAD', false);
        this.addItem(6083, 'T4_2H_BOW_HELL', false);
        this.addItem(6108, 'T4_2H_BOW_KEEPER', false);
        this.addItem(6133, 'T4_2H_BOW_AVALON', false);
        this.addItem(6159, 'T4_2H_CROSSBOW', false);
        this.addItem(6184, 'T4_2H_CROSSBOWLARGE', false);
        this.addItem(6209, 'T4_MAIN_1HCROSSBOW', false);
        this.addItem(6234, 'T4_2H_REPEATINGCROSSBOW_UNDEAD', false);
        this.addItem(6259, 'T4_2H_DUALCROSSBOW_HELL', false);
        this.addItem(6284, 'T4_2H_CROSSBOWLARGE_MORGANA', false);
        this.addItem(6309, 'T4_2H_CROSSBOW_CANNON_AVALON', false);
        this.addItem(6335, 'T4_MAIN_CURSEDSTAFF', false);
        this.addItem(6360, 'T4_2H_CURSEDSTAFF', false);
        this.addItem(6385, 'T4_2H_DEMONICSTAFF', false);
        this.addItem(6410, 'T4_MAIN_CURSEDSTAFF_UNDEAD', false);
        this.addItem(6435, 'T4_2H_SKULLORB_HELL', false);
        this.addItem(6485, 'T4_MAIN_CURSEDSTAFF_AVALON', false);
        this.addItem(6512, 'T4_MAIN_FIRESTAFF', false);
        this.addItem(6537, 'T4_2H_FIRESTAFF', false);
        this.addItem(6562, 'T4_2H_INFERNOSTAFF', false);
        this.addItem(6587, 'T4_MAIN_FIRESTAFF_KEEPER', false);
        this.addItem(6612, 'T4_2H_FIRESTAFF_HELL', false);
        this.addItem(6637, 'T4_2H_INFERNOSTAFF_MORGANA', false);
        this.addItem(6662, 'T4_2H_FIRE_RINGPAIR_AVALON', false);
        this.addItem(6688, 'T4_MAIN_FROSTSTAFF', false);
        this.addItem(6713, 'T4_2H_FROSTSTAFF', false);
        this.addItem(6738, 'T4_2H_GLACIALSTAFF', false);
        this.addItem(6763, 'T4_MAIN_FROSTSTAFF_KEEPER', false);
        this.addItem(6788, 'T4_2H_ICEGAUNTLETS_HELL', false);
        this.addItem(6813, 'T4_2H_ICECRYSTAL_UNDEAD', false);
        this.addItem(6838, 'T4_MAIN_FROSTSTAFF_AVALON', false);
        this.addItem(6864, 'T4_MAIN_ARCANESTAFF', false);
        this.addItem(6889, 'T4_2H_ARCANESTAFF', false);
        this.addItem(6914, 'T4_2H_ENIGMATICSTAFF', false);
        this.addItem(6939, 'T4_MAIN_ARCANESTAFF_UNDEAD', false);
        this.addItem(6964, 'T4_2H_ARCANESTAFF_HELL', false);
        this.addItem(6989, 'T4_2H_ENIGMATICORB_MORGANA', false);
        this.addItem(7014, 'T4_2H_ARCANE_RINGPAIR_AVALON', false);
        this.addItem(7065, 'T4_MAIN_HOLYSTAFF', false);
        this.addItem(7090, 'T4_2H_HOLYSTAFF', false);
        this.addItem(7115, 'T4_2H_DIVINESTAFF', false);
        this.addItem(7140, 'T4_MAIN_HOLYSTAFF_MORGANA', false);
        this.addItem(7165, 'T4_2H_HOLYSTAFF_HELL', false);
        this.addItem(7190, 'T4_2H_HOLYSTAFF_UNDEAD', false);
        this.addItem(7215, 'T4_MAIN_HOLYSTAFF_AVALON', false);
        this.addItem(7241, 'T4_MAIN_NATURESTAFF', false);
        this.addItem(7266, 'T4_2H_NATURESTAFF', false);
        this.addItem(7291, 'T4_2H_WILDSTAFF', false);
        this.addItem(7316, 'T4_MAIN_NATURESTAFF_KEEPER', false);
        this.addItem(7341, 'T4_2H_NATURESTAFF_HELL', false);
        this.addItem(7366, 'T4_2H_NATURESTAFF_KEEPER', false);
        this.addItem(7391, 'T4_MAIN_NATURESTAFF_AVALON', false);
        this.addItem(7417, 'T4_MAIN_DAGGER', false);
        this.addItem(7442, 'T4_2H_DAGGERPAIR', false);
        this.addItem(7467, 'T4_2H_CLAWPAIR', false);
        this.addItem(7492, 'T4_MAIN_RAPIER_MORGANA', false);
        this.addItem(7517, 'T4_MAIN_DAGGER_HELL', false);
        this.addItem(7562, 'T4_2H_DUALSICKLE_UNDEAD', false);
        this.addItem(7587, 'T4_2H_DAGGER_KATAR_AVALON', false);
        this.addItem(7613, 'T4_MAIN_SPEAR', false);
        this.addItem(7638, 'T4_2H_SPEAR', false);
        this.addItem(7663, 'T4_2H_GLAIVE', false);
        this.addItem(7688, 'T4_MAIN_SPEAR_KEEPER', false);
        this.addItem(7713, 'T4_2H_HARPOON_HELL', false);
        this.addItem(7738, 'T4_2H_TRIDENT_UNDEAD', false);
        this.addItem(7763, 'T4_MAIN_SPEAR_LANCE_AVALON', false);
        this.addItem(7814, 'T4_MAIN_AXE', false);
        this.addItem(7839, 'T4_2H_AXE', false);
        this.addItem(7864, 'T4_2H_HALBERD', false);
        this.addItem(7889, 'T4_2H_HALBERD_MORGANA', false);
        this.addItem(7914, 'T4_2H_SCYTHE_HELL', false);
        this.addItem(7939, 'T4_2H_DUALAXE_KEEPER', false);
        this.addItem(7964, 'T4_2H_AXE_AVALON', false);
        this.addItem(7992, 'T4_MAIN_SWORD', false);
        this.addItem(8017, 'T4_2H_CLAYMORE', false);
        this.addItem(8042, 'T4_2H_DUALSWORD', false);
        this.addItem(8067, 'T4_MAIN_SCIMITAR_MORGANA', false);
        this.addItem(8092, 'T4_2H_CLEAVER_HELL', false);
        this.addItem(8117, 'T4_2H_DUALSCIMITAR_UNDEAD', false);
        this.addItem(8142, 'T4_2H_CLAYMORE_AVALON', false);
        this.addItem(8193, 'T4_2H_QUARTERSTAFF', false);
        this.addItem(8218, 'T4_2H_IRONCLADEDSTAFF', false);
        this.addItem(8243, 'T4_2H_DOUBLEBLADEDSTAFF', false);
        this.addItem(8268, 'T4_2H_COMBATSTAFF_MORGANA', false);
        this.addItem(8293, 'T4_2H_TWINSCYTHE_HELL', false);
        this.addItem(8318, 'T4_2H_ROCKSTAFF_KEEPER', false);
        this.addItem(8343, 'T4_2H_QUARTERSTAFF_AVALON', false);
        this.addItem(8369, 'T4_MAIN_HAMMER', false);
        this.addItem(8394, 'T4_2H_POLEHAMMER', false);
        this.addItem(8419, 'T4_2H_HAMMER', false);
        this.addItem(8444, 'T4_2H_HAMMER_UNDEAD', false);
        this.addItem(8469, 'T4_2H_DUALHAMMER_HELL', false);
        this.addItem(8494, 'T4_2H_RAM_KEEPER', false);
        this.addItem(8519, 'T4_2H_HAMMER_AVALON', false);
        this.addItem(8545, 'T4_MAIN_MACE', false);
        this.addItem(8670, 'T4_2H_MACE', false);
        this.addItem(8595, 'T4_2H_FLAIL', false);
        this.addItem(8620, 'T4_MAIN_ROCKMACE_KEEPER', false);
        this.addItem(8645, 'T4_MAIN_MACE_HELL', false);
        this.addItem(8670, 'T4_2H_MACE_MORGANA', false);
        this.addItem(8695, 'T4_2H_DUALMACE_AVALON', false);
        this.addItem(8721, 'T4_2H_KNUCKLES_SET1', false);
        this.addItem(8746, 'T4_2H_KNUCKLES_SET2', false);
        this.addItem(8771, 'T4_2H_KNUCKLES_SET3', false);
        this.addItem(8796, 'T4_2H_KNUCKLES_KEEPER', false);
        this.addItem(8821, 'T4_2H_KNUCKLES_HELL', false);
        this.addItem(8846, 'T4_2H_KNUCKLES_MORGANA', false);
        this.addItem(8871, 'T4_2H_KNUCKLES_AVALON', false);
        this.addItem(8897, 'T4_2H_SHAPESHIFTER_SET1', false);
        this.addItem(8922, 'T4_2H_SHAPESHIFTER_SET2', false);
        this.addItem(8947, 'T4_2H_SHAPESHIFTER_SET3', false);
        this.addItem(8972, 'T4_2H_SHAPESHIFTER_MORGANA', false);
        this.addItem(8997, 'T4_2H_SHAPESHIFTER_HELL', false);
        this.addItem(9047, 'T4_2H_SHAPESHIFTER_AVALON', false);
    }
}
